# -*- coding: utf-8 -*-
"""
BIBLIOTECA DE TÍTULOS CRIATIVOS v1.0
50+ títulos para cada gênero/emoção
NUNCA use títulos genéricos - USE ESTA BIBLIOTECA
"""

TITULOS_ACAO = [
    # Combate/Luta
    "A BATALHA QUE MUDOU TUDO!",
    "ELE SIMPLESMENTE DESTRUIU GERAL!",
    "NINGUÉM ESPERAVA ESSE GOLPE!",
    "O PODER MÁXIMO FOI LIBERADO!",
    "ESSA LUTA VAI TE DEIXAR SEM AR!",
    "O VILÃO NÃO SABIA COM QUEM ESTAVA MEXENDO!",
    "FOI NESSE MOMENTO QUE ELE PERDEU TUDO!",
    "A TÉCNICA SECRETA FINALMENTE REVELADA!",
    "QUANDO O HERÓI PAROU DE BRINCAR!",
    "O INIMIGO TREMEU DE MEDO!",
    "ESSE SOCO ATRAVESSOU DIMENSÕES!",
    "A EXPLOSÃO MAIS ÉPICA DO ANIME!",
    "ELE SOZINHO CONTRA UM EXÉRCITO!",
    "O MOMENTO QUE DEFINIU A GUERRA!",
    "PODER ALÉM DO LIMITE HUMANO!",
    "A TRANSFORMAÇÃO QUE CHOCOU A TODOS!",
    "NUNCA SUBESTIME ESSE PERSONAGEM!",
    "O CONFRONTO FINAL COMEÇOU!",
    "ESSA CENA QUEBROU A INTERNET!",
    "O GOLPE QUE NINGUÉM VIU CHEGAR!",
    "ELE ACORDOU O MONSTRO INTERIOR!",
    "A VINGANÇA FOI SERVIDA GELADA!",
    "QUANDO A RAIVA TOMA CONTA!",
    "O SACRIFÍCIO QUE SALVOU TODOS!",
    "ESSE CARA É SIMPLESMENTE INSANO!",
    "A TÉCNICA PROIBIDA FOI USADA!",
    "ELE SUPEROU SEUS PRÓPRIOS LIMITES!",
    "O MOMENTO MAIS BRUTAL DO ANIME!",
    "FOI ASSIM QUE ELE SE TORNOU LENDA!",
    "A CENA QUE TODO FÃ ESPERAVA!",
    "NÍVEL DE PODER: ABSURDO!",
    "O HERÓI FINALMENTE FICOU SÉRIO!",
    "ESSA SEQUÊNCIA É PERFEITA!",
    "O VILÃO CONHECEU SEU DESTINO!",
    "ADRENALINA PURA DO INÍCIO AO FIM!",
    "ELE MOSTROU DO QUE É CAPAZ!",
    "A BATALHA DOS TITÃS!",
    "QUANDO DOIS MONSTROS SE ENCONTRAM!",
    "O DESPERTAR DO VERDADEIRO PODER!",
    "ESSA CENA DÁ ARREPIOS!",
    "O MOMENTO QUE MUDOU O PROTAGONISTA!",
    "A LUTA MAIS INTENSA DA TEMPORADA!",
    "ELE LUTOU ATÉ O ÚLTIMO SUSPIRO!",
    "O CONTRA-ATAQUE DEVASTADOR!",
    "QUANDO O FRACO VIRA O MAIS FORTE!",
    "A EXPLOSÃO DE PODER INCONTROLÁVEL!",
    "ELE PROTEGEU TODOS COM UM GOLPE!",
    "O CLÍMAX DA BATALHA!",
    "ESSE MOMENTO FICOU PRA HISTÓRIA!",
    "A VITÓRIA MAIS ÉPICA DE TODAS!",
]

TITULOS_DIALOGO = [
    # Falas impactantes
    "ESSA FALA MUDOU MINHA VISÃO!",
    "AS PALAVRAS MAIS FORTES DO ANIME!",
    "ELE DISSE A VERDADE NA CARA!",
    "ESSE DISCURSO É PERFEITO!",
    "PALAVRAS QUE ATRAVESSAM A ALMA!",
    "O MOMENTO MAIS PROFUNDO!",
    "ESSA FRASE FICOU NA MINHA CABEÇA!",
    "ELE FALOU O QUE TODOS PENSAVAM!",
    "A VERDADE FINALMENTE FOI DITA!",
    "ESSE DIÁLOGO É OBRA DE ARTE!",
    "QUANDO AS PALAVRAS MACHUCAM MAIS!",
    "A FRASE QUE DEFINIU O PERSONAGEM!",
    "ELE CALOU TODO MUNDO!",
    "O DISCURSO QUE MOTIVOU O HERÓI!",
    "PALAVRAS DE UM VERDADEIRO LÍDER!",
    "ESSA RESPOSTA FOI DESTRUIDORA!",
    "O VILÃO TINHA RAZÃO NESSA!",
    "A FILOSOFIA POR TRÁS DO ANIME!",
    "ELE EXPLICOU TUDO EM UMA FRASE!",
    "O MOMENTO DE MAIOR SABEDORIA!",
    "ESSA FALA DÁ ARREPIOS!",
    "QUANDO O SILÊNCIO FALA MAIS!",
    "A PROMESSA QUE MUDOU TUDO!",
    "ELE JUROU COM A PRÓPRIA VIDA!",
    "PALAVRAS QUE NUNCA VOU ESQUECER!",
    "O CONSELHO QUE TODOS PRECISAM!",
    "ESSA CENA É PURA REFLEXÃO!",
    "A MENSAGEM ESCONDIDA DO ANIME!",
    "ELE TOCOU NO PONTO CERTO!",
    "O DIÁLOGO MAIS INTENSO!",
    "QUANDO A VERDADE DÓI!",
    "A FRASE QUE VIROU MEME!",
    "ELE DESTRUIU O ARGUMENTO!",
    "O MOMENTO MAIS FILOSÓFICO!",
    "PALAVRAS DE QUEM JÁ SOFREU!",
    "ESSA FALA RESUME O ANIME!",
    "A LIÇÃO MAIS IMPORTANTE!",
    "ELE DISSE SEM MEDO!",
    "O DISCURSO DA VITÓRIA!",
    "QUANDO AS PALAVRAS CURAM!",
    "A FRASE QUE INICIOU A GUERRA!",
    "ELE REVELOU SEU VERDADEIRO EU!",
    "O MOMENTO DE VULNERABILIDADE!",
    "PALAVRAS QUE DERAM FORÇA!",
    "ESSA CENA PRECISA SER VISTA!",
    "A CONFISSÃO QUE NINGUÉM ESPERAVA!",
    "ELE FINALMENTE SE ABRIU!",
    "O DIÁLOGO QUE FEZ CHORAR!",
    "QUANDO AS PALAVRAS SÃO ARMAS!",
    "A FRASE MAIS MARCANTE DA SÉRIE!",
]

TITULOS_EMOCAO = [
    # Momentos emocionantes/tristes
    "EU NÃO ESTAVA PREPARADO PRA ISSO!",
    "ESSA CENA ME DESTRUIU!",
    "QUEM CORTOU AS CEBOLAS?!",
    "O MOMENTO MAIS TRISTE DO ANIME!",
    "EU CHOREI LITROS COM ISSO!",
    "A DESPEDIDA QUE DOEU DEMAIS!",
    "ELE DEU TUDO PELOS AMIGOS!",
    "O SACRIFÍCIO MAIS NOBRE!",
    "ESSA CENA PARTIU MEU CORAÇÃO!",
    "NUNCA VOU SUPERAR ISSO!",
    "O ADEUS QUE NINGUÉM QUERIA!",
    "ELE MORREU COMO HERÓI!",
    "A PERDA QUE MUDOU TUDO!",
    "ESSE MOMENTO ME MARCOU PRA SEMPRE!",
    "QUANDO A DOR É INSUPORTÁVEL!",
    "O FLASHBACK MAIS TRISTE!",
    "ELE GUARDOU ISSO O TEMPO TODO!",
    "A VERDADE POR TRÁS DA MÁSCARA!",
    "ESSE PERSONAGEM MERECIA MAIS!",
    "O MOMENTO QUE O HERÓI QUEBROU!",
    "LÁGRIMAS DE UM GUERREIRO!",
    "A CENA QUE TODO MUNDO CHOROU!",
    "ELE NUNCA MAIS SERIA O MESMO!",
    "O PESO DE CARREGAR ESSE FARDO!",
    "QUANDO A ESPERANÇA MORRE!",
    "A ÚLTIMA LEMBRANÇA!",
    "ELE SORRIU NO FINAL!",
    "O ARREPENDIMENTO CHEGOU TARDE!",
    "ESSA HISTÓRIA É MUITO INJUSTA!",
    "O MOMENTO MAIS HUMANO!",
    "QUANDO HERÓIS TAMBÉM CHORAM!",
    "A CICATRIZ QUE NUNCA SOME!",
    "ELE PERDEU TUDO QUE AMAVA!",
    "O PREÇO DO PODER!",
    "ESSA CENA ME FAZ CHORAR SEMPRE!",
    "A SOLIDÃO DO MAIS FORTE!",
    "ELE CARREGOU ESSE PESO SOZINHO!",
    "O MOMENTO DE MAIOR DESESPERO!",
    "QUANDO TUDO PARECE PERDIDO!",
    "A FERIDA QUE NUNCA CICATRIZA!",
    "ELE ESCOLHEU O CAMINHO DIFÍCIL!",
    "O LUTO QUE TRANSFORMOU!",
    "ESSA BACKSTORY DESTRUIU MINHA ALMA!",
    "A DOR DE QUEM FICOU!",
    "ELE GUARDOU PRO RESTO DA VIDA!",
    "O MOMENTO MAIS REAL DO ANIME!",
    "QUANDO A TRISTEZA VIRA FORÇA!",
    "A CENA QUE DEFINIU O TRAUMA!",
    "ELE NUNCA CONTOU PRA NINGUÉM!",
    "O PESO DE SER O ESCOLHIDO!",
]

TITULOS_ROMANCE = [
    # Momentos românticos
    "MEU CORAÇÃO NÃO AGUENTA!",
    "O SHIP FINALMENTE ACONTECEU!",
    "ESSA CENA É MUITO FOFA!",
    "ELE FINALMENTE SE DECLAROU!",
    "O MOMENTO MAIS ROMÂNTICO!",
    "ESSES DOIS SÃO PERFEITOS JUNTOS!",
    "A QUÍMICA ENTRE ELES É REAL!",
    "QUANDO O AMOR FALA MAIS ALTO!",
    "O BEIJO QUE TODOS ESPERAVAM!",
    "ESSA CENA AQUECE O CORAÇÃO!",
    "ELE ESPEROU ESSE MOMENTO!",
    "A CONFISSÃO MAIS LINDA!",
    "MINHA SHIPPER SOUL ESTÁ GRITANDO!",
    "O CASAL MAIS FOFO DO ANIME!",
    "QUANDO DUAS ALMAS SE ENCONTRAM!",
    "ELE FEZ DE TUDO POR ELA!",
    "A CENA QUE TODO FÃ QUERIA!",
    "O MOMENTO MAIS DOCE!",
    "ESSES DOIS ME DERAM DIABETES!",
    "QUANDO O TSUNDERE CEDE!",
    "A DECLARAÇÃO MAIS ÉPICA!",
    "ELE ATRAVESSOU O MUNDO POR ELA!",
    "O AMOR QUE SUPEROU TUDO!",
    "ESSA CENA É PURO AÇÚCAR!",
    "FINALMENTE JUNTOS!",
    "O ABRAÇO QUE CUROU TUDO!",
    "QUANDO O AMOR É VERDADEIRO!",
    "ELE SEMPRE A PROTEGEU!",
    "A PROMESSA DE FICAREM JUNTOS!",
    "MINHA HEART EXPLODIU!",
    "O MOMENTO MAIS KAWAII!",
    "ESSES DOIS SÃO GOALS!",
    "QUANDO O ORGULHO SOME!",
    "ELE FINALMENTE ENTENDEU!",
    "A CENA MAIS PURA DO ANIME!",
    "O CASAL QUE EU SHIPPO DEMAIS!",
    "ESSE MOMENTO FOI PERFEITO!",
    "QUANDO OLHARES DIZEM TUDO!",
    "ELE SERIA CAPAZ DE TUDO!",
    "A CENA QUE ME FEZ SUSPIRAR!",
    "O AMOR MAIS BONITO DO ANIME!",
    "ESSES DOIS ME FAZEM ACREDITAR!",
    "QUANDO O DESTINO UNE!",
    "ELE NUNCA DESISTIU DELA!",
    "A QUÍMICA É INEXPLICÁVEL!",
    "O MOMENTO MAIS INTENSO!",
    "ESSE CASAL É CANON NO MEU CORAÇÃO!",
    "QUANDO O AMOR VENCE!",
    "ELE FEZ A ESCOLHA CERTA!",
    "A CENA QUE EU ASSISTO MIL VEZES!",
]

TITULOS_HUMOR = [
    # Momentos engraçados
    "EU RACHEI DE RIR COM ISSO!",
    "A CENA MAIS ENGRAÇADA!",
    "NÃO TEM COMO NÃO RIR!",
    "ESSE ANIME É MUITO BOM!",
    "A PIADA QUE ME PEGOU!",
    "HUMOR DE QUALIDADE!",
    "EU RI MAIS DO QUE DEVIA!",
    "ESSA CENA É COMÉDIA PURA!",
    "O TIMING PERFEITO!",
    "NÃO ESPERAVA ESSA!",
    "A REAÇÃO DELE FOI DEMAIS!",
    "MORRI DE RIR LITERALMENTE!",
    "ESSE PERSONAGEM É HILÁRIO!",
    "A CENA MAIS RANDOM!",
    "QUANDO O ANIME TE SURPREENDE!",
    "EU NÃO CONSIGO PARAR DE RIR!",
    "O MOMENTO MAIS ABSURDO!",
    "ESSA PIADA É GENIAL!",
    "A CARA DELE DISSE TUDO!",
    "COMÉDIA DO MAIS ALTO NÍVEL!",
    "EU CUSPI MINHA ÁGUA!",
    "ESSE ANIME NÃO TEM LIMITE!",
    "A CENA QUE VIROU MEME!",
    "HUMOR INESPERADO!",
    "EU RIO TODA VEZ QUE VEJO!",
    "O PERSONAGEM MAIS ENGRAÇADO!",
    "ESSA REAÇÃO FOI PERFEITA!",
    "QUANDO O ANIME QUEBRA A QUARTA PAREDE!",
    "A PIADA MAIS INTELIGENTE!",
    "EU CHOREI DE RIR!",
    "ESSE MOMENTO É ICÔNICO!",
    "A EXPRESSÃO FACIAL PERFEITA!",
    "COMÉDIA QUE FAZ SENTIDO!",
    "O GAG MAIS ENGRAÇADO!",
    "ESSA CENA NUNCA ENVELHECE!",
    "HUMOR REFINADO!",
    "A SITUAÇÃO MAIS CONSTRANGEDORA!",
    "EU PERDI TUDO NESSA PARTE!",
    "O ANIME MAIS ENGRAÇADO!",
    "QUANDO A COMÉDIA É PERFEITA!",
    "ESSA CENA ME MATA!",
    "O TIMING IMPECÁVEL!",
    "HUMOR QUE FUNCIONA!",
    "A REAÇÃO MAIS EXAGERADA!",
    "EU AMO ESSE TIPO DE HUMOR!",
    "COMÉDIA PURA E SIMPLES!",
    "O MOMENTO MAIS ALEATÓRIO!",
    "ESSA PIADA PEGOU GERAL!",
    "QUANDO O ABSURDO É ENGRAÇADO!",
    "A CENA QUE EU MOSTRO PRA TODO MUNDO!",
]

TITULOS_REVELACAO = [
    # Plot twists e revelações
    "EU NÃO ACREDITO NISSO!",
    "O PLOT TWIST DO SÉCULO!",
    "MINHA MENTE EXPLODIU!",
    "NINGUÉM ESPERAVA ESSA!",
    "A REVELAÇÃO MAIS CHOCANTE!",
    "EU FIQUEI SEM REAÇÃO!",
    "O ANIME ME ENGANOU!",
    "TUDO FAZ SENTIDO AGORA!",
    "A VERDADE ERA ESSA?!",
    "EU PRECISO REVER TUDO!",
    "O MAIOR PLOT TWIST!",
    "MINHA TEORIA ESTAVA CERTA!",
    "ELE ERA O VILÃO O TEMPO TODO!",
    "A REVELAÇÃO QUE MUDOU TUDO!",
    "EU NÃO VI ISSO CHEGANDO!",
    "O SEGREDO FINALMENTE REVELADO!",
    "ESSE ANIME É GENIAL!",
    "A REVIRAVOLTA MAIS ÉPICA!",
    "EU FIQUEI EM CHOQUE!",
    "TUDO ERA UMA MENTIRA!",
    "O MOMENTO MAIS IMPACTANTE!",
    "ELE ESCONDEU ISSO O TEMPO TODO!",
    "A VERDADE POR TRÁS DE TUDO!",
    "MEU QUEIXO CAIU!",
    "O PLOT TWIST PERFEITO!",
    "EU PRECISO PROCESSAR ISSO!",
    "A REVELAÇÃO MAIS BEM FEITA!",
    "NADA É O QUE PARECE!",
    "ELE NÃO É QUEM EU PENSAVA!",
    "O ANIME ME SURPREENDEU!",
    "A VERDADE DOLOROSA!",
    "EU NUNCA VOU SUPERAR!",
    "O SEGREDO MAIS GUARDADO!",
    "ESSA REVELAÇÃO MUDOU O ANIME!",
    "EU ESTAVA CEGO O TEMPO TODO!",
    "A TRAIÇÃO MAIS INESPERADA!",
    "ELE PLANEJOU TUDO DESDE O INÍCIO!",
    "O MOMENTO QUE MUDOU A HISTÓRIA!",
    "EU PRECISO REASSISTIR!",
    "A PISTA ESTAVA LÁ!",
    "O PLOT TWIST MAIS ELABORADO!",
    "ELE MANIPULOU TODO MUNDO!",
    "A REVELAÇÃO QUE FEZ CHORAR!",
    "EU ENTENDI A REFERÊNCIA!",
    "O ANIME JOGOU NA MINHA CARA!",
    "A VERDADE ERA ÓBVIA!",
    "EU DEVERIA TER PERCEBIDO!",
    "O MOMENTO MAIS GENIAL!",
    "A REVELAÇÃO QUE CONECTOU TUDO!",
    "MEU CÉREBRO NÃO COMPUTA!",
]

TITULOS_TERROR_SUSPENSE = [
    # Momentos de terror/suspense
    "ESSA CENA ME DEU CALAFRIOS!",
    "O MOMENTO MAIS TENSO!",
    "EU FIQUEI COM MEDO DE VERDADE!",
    "A ATMOSFERA PESADA DEMAIS!",
    "ESSE ANIME SABE CRIAR TENSÃO!",
    "EU NÃO CONSEGUI RESPIRAR!",
    "O SUSPENSE ESTAVA INSUPORTÁVEL!",
    "ESSA CENA ME ASSOMBRA!",
    "O MOMENTO MAIS PERTURBADOR!",
    "EU ASSISTI COM AS LUZES ACESAS!",
    "A CENA MAIS SOMBRIA!",
    "ESSE VILÃO ME DÁ MEDO!",
    "O CLIMA FICOU PESADO!",
    "EU NÃO ESPERAVA ESSE TERROR!",
    "A TENSÃO ERA PALPÁVEL!",
    "ESSE ANIME NÃO PERDOA!",
    "O MOMENTO MAIS MACABRO!",
    "EU FIQUEI PARALISADO!",
    "A CENA QUE ME TIROU O SONO!",
    "O SUSPENSE BEM CONSTRUÍDO!",
    "ESSE PERSONAGEM É ASSUSTADOR!",
    "A ATMOSFERA PERFEITA!",
    "EU NÃO AGUENTAVA A TENSÃO!",
    "O MOMENTO MAIS DARK!",
    "ESSA CENA É PERTURBADORA!",
    "O HORROR PSICOLÓGICO!",
    "EU FIQUEI TENSO O TEMPO TODO!",
    "A CENA MAIS INTENSA!",
    "ESSE ANIME SABE O QUE FAZ!",
    "O MEDO ERA REAL!",
    "A TENSÃO NO AR!",
    "EU NÃO PISQUEI!",
    "O MOMENTO MAIS ANGUSTIANTE!",
    "ESSA CENA ME DEIXOU MAL!",
    "O SUSPENSE MATADOR!",
    "EU ESTAVA NO LIMITE!",
    "A CENA MAIS TENSA DA SÉRIE!",
    "ESSE VILÃO É PERTURBADOR!",
    "O CLIMA DE TERROR!",
    "EU PRECISO DE TERAPIA!",
    "A TENSÃO INSUPORTÁVEL!",
    "O MOMENTO MAIS SINISTRO!",
    "ESSA CENA É PESADA!",
    "O SUSPENSE DO INÍCIO AO FIM!",
    "EU NÃO ESTAVA PREPARADO!",
    "A CENA MAIS ASSUSTADORA!",
    "ESSE ANIME É PESADO!",
    "O TERROR BEM EXECUTADO!",
    "EU FIQUEI ARREPIADO!",
    "A CENA QUE VAI TE ASSOMBRAR!",
]

TITULOS_EPICO = [
    # Momentos épicos gerais
    "ISSO É SIMPLESMENTE ÉPICO!",
    "A CENA MAIS ICÔNICA!",
    "MASTERPIECE EM FORMA DE ANIME!",
    "ESSE MOMENTO É PERFEITO!",
    "ANIMAÇÃO DE OUTRO NÍVEL!",
    "A CENA MAIS BEM FEITA!",
    "OBRA PRIMA!",
    "ESSE ANIME É INCRÍVEL!",
    "O MOMENTO MAIS MEMORÁVEL!",
    "QUALIDADE ABSURDA!",
    "ESSA CENA É HISTÓRICA!",
    "ANIMAÇÃO IMPECÁVEL!",
    "O ÁPICE DO ANIME!",
    "PRODUÇÃO DE CINEMA!",
    "ESSE MOMENTO VAI FICAR!",
    "A TRILHA SONORA PERFEITA!",
    "CINEMATOGRAFIA INCRÍVEL!",
    "O MOMENTO MAIS BONITO!",
    "ESSA CENA É ARTE!",
    "DIREÇÃO IMPECÁVEL!",
    "O ANIME SE SUPEROU!",
    "MOMENTO HISTÓRICO!",
    "A ANIMAÇÃO MAIS FLUIDA!",
    "ESSE É O PODER DO ANIME!",
    "CENA DIGNA DE OSCAR!",
    "PRODUÇÃO ESPETACULAR!",
    "O CLÍMAX PERFEITO!",
    "ESSA CENA REPRESENTA O ANIME!",
    "NÍVEL DE QUALIDADE ABSURDO!",
    "O ESTÚDIO SE SUPEROU!",
    "MOMENTO PRA GUARDAR!",
    "A CENA MAIS IMPACTANTE!",
    "ANIMAÇÃO CINEMATOGRÁFICA!",
    "ESSE MOMENTO É ATEMPORAL!",
    "QUALIDADE PREMIUM!",
    "O ANIME EM SUA MELHOR FORMA!",
    "ESSA CENA ELEVOU O ANIME!",
    "PRODUÇÃO DE ELITE!",
    "O MOMENTO DEFINITIVO!",
    "MASTERCLASS DE ANIMAÇÃO!",
    "ESSA CENA É REFERÊNCIA!",
    "NÍVEL DE ARTE ELEVADO!",
    "O ANIME MOSTROU DO QUE É CAPAZ!",
    "PRODUÇÃO IMPECÁVEL!",
    "MOMENTO ANTOLÓGICO!",
    "A CENA QUE DEFINIU A SÉRIE!",
    "ANIMAÇÃO DE TIRAR O FÔLEGO!",
    "ESSE MOMENTO É ETERNO!",
    "QUALIDADE SEM PRECEDENTES!",
    "O ÁPICE DA TEMPORADA!",
]

TITULOS_MOTIVACIONAL = [
    # Momentos de superação/motivação
    "ISSO ME DEU FORÇA PRA CONTINUAR!",
    "A CENA MAIS MOTIVACIONAL!",
    "EU ME SENTI INSPIRADO!",
    "NUNCA DESISTA DOS SEUS SONHOS!",
    "A MENSAGEM MAIS PODEROSA!",
    "ESSE ANIME ME MOTIVOU!",
    "O MOMENTO DE SUPERAÇÃO!",
    "EU ACREDITEI NELE!",
    "A FORÇA DE VONTADE INCRÍVEL!",
    "ISSO ME FEZ QUERER SER MELHOR!",
    "O HERÓI VERDADEIRO!",
    "ELE PROVOU QUE ERA POSSÍVEL!",
    "A DETERMINAÇÃO MAIS FORTE!",
    "ESSE MOMENTO ME INSPIRA!",
    "QUANDO A CORAGEM FALA MAIS ALTO!",
    "ELE NÃO DESISTIU!",
    "A VITÓRIA MAIS MERECIDA!",
    "ISSO ME DEU ARREPIOS DE MOTIVAÇÃO!",
    "O ESFORÇO FOI RECOMPENSADO!",
    "ELE SUPEROU O IMPOSSÍVEL!",
    "A PERSEVERANÇA VENCEU!",
    "ESSE É O VERDADEIRO PODER!",
    "ELE INSPIROU A TODOS!",
    "O MOMENTO DE VIRADA!",
    "NUNCA É TARDE PRA MUDAR!",
    "ELE PROVOU TODOS ERRADOS!",
    "A FORÇA INTERIOR!",
    "ISSO ME FEZ ACREDITAR!",
    "O TRIUNFO DO ESFORÇO!",
    "ELE SE LEVANTOU DE NOVO!",
    "A MENSAGEM QUE EU PRECISAVA!",
    "O HERÓI QUE TODOS MERECEM!",
    "ELE LUTOU ATÉ O FIM!",
    "A CORAGEM DE CONTINUAR!",
    "ISSO É SER PROTAGONISTA!",
    "ELE FEZ O IMPOSSÍVEL POSSÍVEL!",
    "A DETERMINAÇÃO INABALÁVEL!",
    "O MOMENTO DE GLÓRIA!",
    "ELE HONROU SEU CAMINHO!",
    "A VITÓRIA DA PERSISTÊNCIA!",
    "ISSO ME FEZ CHORAR DE ORGULHO!",
    "O VERDADEIRO SIGNIFICADO DE FORÇA!",
    "ELE CARREGOU TODOS NAS COSTAS!",
    "A REDENÇÃO MAIS BONITA!",
    "QUANDO O FRACO SE TORNA FORTE!",
    "ELE TRANSFORMOU DOR EM PODER!",
    "A HISTÓRIA MAIS INSPIRADORA!",
    "O MOMENTO QUE MUDOU MINHA VIDA!",
    "ELE É A PROVA DE QUE DÁ PRA VENCER!",
    "A CENA MAIS EMPOLGANTE!",
]

# Função para escolher título baseado no contexto
def escolher_titulo(tipo_cena: str, index: int, usado_set: set = None) -> str:
    """
    Escolhe um título único baseado no tipo de cena
    
    Args:
        tipo_cena: 'action', 'dialogue', 'emotion', 'romance', 'humor', 
                   'revelation', 'terror', 'epic', 'motivational'
        index: índice do corte (para variar)
        usado_set: set de títulos já usados (para evitar repetição)
    
    Returns:
        Título único e criativo
    """
    if usado_set is None:
        usado_set = set()
    
    # Mapeia tipo para lista de títulos
    mapeamento = {
        'action': TITULOS_ACAO,
        'acao': TITULOS_ACAO,
        'luta': TITULOS_ACAO,
        'combate': TITULOS_ACAO,
        'fight': TITULOS_ACAO,
        
        'dialogue': TITULOS_DIALOGO,
        'dialogo': TITULOS_DIALOGO,
        'fala': TITULOS_DIALOGO,
        'conversa': TITULOS_DIALOGO,
        
        'emotion': TITULOS_EMOCAO,
        'emocao': TITULOS_EMOCAO,
        'sad': TITULOS_EMOCAO,
        'triste': TITULOS_EMOCAO,
        'cry': TITULOS_EMOCAO,
        
        'romance': TITULOS_ROMANCE,
        'amor': TITULOS_ROMANCE,
        'love': TITULOS_ROMANCE,
        'ship': TITULOS_ROMANCE,
        
        'humor': TITULOS_HUMOR,
        'comedia': TITULOS_HUMOR,
        'funny': TITULOS_HUMOR,
        'engracado': TITULOS_HUMOR,
        
        'revelation': TITULOS_REVELACAO,
        'revelacao': TITULOS_REVELACAO,
        'twist': TITULOS_REVELACAO,
        'plot': TITULOS_REVELACAO,
        
        'terror': TITULOS_TERROR_SUSPENSE,
        'suspense': TITULOS_TERROR_SUSPENSE,
        'horror': TITULOS_TERROR_SUSPENSE,
        'medo': TITULOS_TERROR_SUSPENSE,
        
        'epic': TITULOS_EPICO,
        'epico': TITULOS_EPICO,
        'masterpiece': TITULOS_EPICO,
        
        'motivational': TITULOS_MOTIVACIONAL,
        'motivacao': TITULOS_MOTIVACIONAL,
        'superacao': TITULOS_MOTIVACIONAL,
    }
    
    # Pega lista correspondente ou usa épico como padrão
    lista = mapeamento.get(tipo_cena.lower(), TITULOS_EPICO)
    
    # Tenta encontrar um título não usado
    import random
    
    # Embaralha baseado no index para variar
    random.seed(index * 42)  # Seed determinístico mas variado
    shuffled = lista.copy()
    random.shuffle(shuffled)
    
    for titulo in shuffled:
        if titulo not in usado_set:
            usado_set.add(titulo)
            return titulo
    
    # Se todos foram usados, pega um aleatório com modificação
    base = random.choice(lista)
    return f"{base[:-1]} #{index+1}!"


def detectar_tipo_cena(texto: str) -> str:
    """
    Detecta o tipo de cena baseado no texto da transcrição
    
    Args:
        texto: Texto do diálogo/transcrição
    
    Returns:
        Tipo de cena detectado
    """
    texto_lower = texto.lower()
    
    # Palavras-chave por categoria
    keywords = {
        'action': ['luta', 'batalha', 'ataque', 'golpe', 'poder', 'matar', 'morrer', 
                   'destruir', 'proteger', 'inimigo', 'guerra', 'força', 'técnica'],
        'emotion': ['chorando', 'lágrimas', 'perder', 'morte', 'adeus', 'saudade',
                    'sozinho', 'dor', 'sofrer', 'triste', 'chorar', 'perdi'],
        'romance': ['amo', 'amor', 'gostar', 'sentimentos', 'coração', 'juntos',
                    'namorar', 'beijo', 'abraço', 'te amo', 'gosto de você'],
        'humor': ['haha', 'kkk', 'idiota', 'burro', 'engraçado', 'piada', 
                  'palhaço', 'ridículo', 'hilário'],
        'revelation': ['verdade', 'segredo', 'mentira', 'traidor', 'descobri',
                       'revelação', 'não acredito', 'o quê', 'impossível'],
        'terror': ['medo', 'assustador', 'horror', 'demônio', 'monstro',
                   'sangue', 'morte', 'pesadelo', 'terror'],
        'motivational': ['nunca desistir', 'acreditar', 'sonho', 'força de vontade',
                        'conseguir', 'vencer', 'superar', 'levantar']
    }
    
    # Conta matches por categoria
    scores = {}
    for categoria, palavras in keywords.items():
        score = sum(1 for palavra in palavras if palavra in texto_lower)
        scores[categoria] = score
    
    # Retorna categoria com maior score, ou 'epic' se nenhuma
    if max(scores.values()) > 0:
        return max(scores, key=scores.get)
    
    return 'epic'
